ServerEvents.compostableRecipes(event=>{
    //event.add("bamboo", 0.125) // 12.5% to increase compost progress
    event.add('meadow:delphinium', 0.125)
    event.add('meadow:saxifrage', 0.125)
    event.add('meadow:enzian', 0.125)
    event.add('meadow:fire_lily', 0.125)
    event.add('meadow:eriophorum', 0.125)
    event.add('meadow:eriophorum_tall', 0.125)
    event.add('meadow:alpine_poppy', 0.125)
    event.add('verdantvibes:candy_tuft', 0.125)
    event.add('verdantvibes:periwinkle', 0.125)
    event.add('verdantvibes:monstera', 0.125)
    event.add('verdantvibes:snake_plant', 0.125)
    event.add('verdantvibes:parlour_palm', 0.125)
    event.add('verdantvibes:money_tree', 0.125)
    event.add('verdantvibes:lobelia', 0.125)
    event.add('verdantvibes:cattails', 0.125)
    event.add('verdantvibes:burnweed', 0.125)
    event.add('verdantvibes:dragon_tree', 0.125)
})