ServerEvents.recipes(event => {

    // All Recipe Removal
    let toRemove = [
        //Removed Recipes
        {output: 'aquaculture:neptunium_helmet'},
        {output: 'aquaculture:neptunium_leggings'},
        {output: 'aquaculture:neptunium_chestplate'},
        {output: 'aquaculture:neptunium_boots'},
        {output: 'aquaculture:neptunium_bow'},
        {output: 'aquaculture:neptunium_sword'},
        {output: 'aquaculture:neptunium_axe'},
        {output: 'aquaculture:neptunes_bounty'},
        {output: 'aquaculture:wooden_fillet_knife'},
        {output: 'aquaculture:stone_fillet_knife'},
        {output: 'aquaculture:iron_fillet_knife'},
        {output: 'aquaculture:gold_fillet_knife'},
        {output: 'aquaculture:diamond_fillet_knife'},
        {output: 'aquaculture:oak_fish_mount'},
        {output: 'aquaculture:spruce_fish_mount'},
        {output: 'aquaculture:birch_fish_mount'},
        {output: 'aquaculture:jungle_fish_mount'},
        {output: 'aquaculture:acacia_fish_mount'},
        {output: 'aquaculture:dark_oak_fish_mount'},
        {output: 'nameless_trinkets:missing_page'}, 
        {output: 'nameless_trinkets:what_magnet'}, 
        {output: 'nameless_trinkets:explosion_proof_jacket'}, 
        {output: 'nameless_trinkets:ghast_eye'}, 
        {output: 'nameless_trinkets:electric_paddle'}, 
        {output: 'nameless_trinkets:sleeping_pills'},
        {output: 'reliquary:magazines/buster_magazine'}, 
        {output: 'reliquary:magazines/concussive_magazine'}, 
        {output: 'reliquary:magazines/ender_magazine'}, 
        {output: 'reliquary:magazines/blaze_magazine'}, 
        {output: 'reliquary:magazines/exorcism_magazine'}, 
        {output: 'reliquary:magazines/neutral_magazine'},
        {output: 'reliquary:magazines/empty_magazine'}, 
        {output: 'reliquary:magazines/seeker_magazine'}, 
        {output: 'reliquary:magazines/sand_magazine'}, 
        {output: 'reliquary:magazines/storm_magazine'},
        {output: 'reliquary:bullets/empty_bullet'}, 
        {output: 'reliquary:bullets/neutral_bullet'}, 
        {output: 'reliquary:bullets/storm_bullet'}, 
        {output: 'reliquary:bullets/sand_bullet'}, 
        {output: 'reliquary:bullets/seeker_bullet'}, 
        {output: 'reliquary:bullets/buster_bullet'}, 
        {output: 'reliquary:bullets/concussive_bullet'}, 
        {output: 'reliquary:bullets/ender_bullet'}, 
        {output: 'reliquary:bullets/blaze_bullet'}, 
        {output: 'reliquary:bullets/exorcism_bullet'},
        {output: 'nameless_trinkets:four_leaf_clover'},
        {output: 'reliquary:rending_gale'},
        {output: 'mysticsbiomes:strawberry_jam'},
        {output: 'mysticsbiomes:glass_jar'},
        {output: 'bakery:dough'},
        {output: 'candlelight:dough'},
        {output: 'create:dough'},
        {output: 'farmingforblockheads:feeding_trough'},
        {output: 'reliquary:midas_touchstone'}, 
        {output: 'reliquary:pyromancer_staff'}, 
        {output: 'reliquary:rod_of_lyssa'},
        {output: 'candlelight:carrot_crate'},
        {output: 'candlelight:potato_crate'},
        {output: 'candlelight:beetroot_crate'}, 
        //Replaced Recipes
        {output: 'mighty_mail:post_box'},
        {output: 'farmersdelight:wheat_dough'},
        {output: 'delightful:cheeseburger'},
        {output: 'delightful:deluxe_cheeseburger'},
        //{output: 'untameddelight:baked_trevally_with_cheese'},
        {output: 'luphieclutteredmod:luphie_mermaid_pearl'},
        {output: 'meadow:oil_lantern'},
    ];
    
      for (const remove of toRemove) {
        event.remove(remove);
    }
})