ServerEvents.recipes(event => {

    // All Recipe Removal
    let toRemove = [
        //Removed Recipes
        {output: 'nameless_trinkets:missing_page'}, 
        {output: 'nameless_trinkets:what_magnet'}, 
        {output: 'nameless_trinkets:explosion_proof_jacket'}, 
        {output: 'nameless_trinkets:ghast_eye'}, 
        {output: 'nameless_trinkets:electric_paddle'}, 
        {output: 'nameless_trinkets:sleeping_pills'},
        {output: 'reliquary:magazines/buster_magazine'}, 
        {output: 'reliquary:magazines/concussive_magazine'}, 
        {output: 'reliquary:magazines/ender_magazine'}, 
        {output: 'reliquary:magazines/blaze_magazine'}, 
        {output: 'reliquary:magazines/exorcism_magazine'}, 
        {output: 'reliquary:magazines/neutral_magazine'},
        {output: 'reliquary:magazines/empty_magazine'}, 
        {output: 'reliquary:magazines/seeker_magazine'}, 
        {output: 'reliquary:magazines/sand_magazine'}, 
        {output: 'reliquary:magazines/storm_magazine'},
        {output: 'reliquary:bullets/empty_bullet'}, 
        {output: 'reliquary:bullets/neutral_bullet'}, 
        {output: 'reliquary:bullets/storm_bullet'}, 
        {output: 'reliquary:bullets/sand_bullet'}, 
        {output: 'reliquary:bullets/seeker_bullet'}, 
        {output: 'reliquary:bullets/buster_bullet'}, 
        {output: 'reliquary:bullets/concussive_bullet'}, 
        {output: 'reliquary:bullets/ender_bullet'}, 
        {output: 'reliquary:bullets/blaze_bullet'}, 
        {output: 'reliquary:bullets/exorcism_bullet'},
        {output: 'nameless_trinkets:four_leaf_clover'},
        {output: 'reliquary:rending_gale'},
        {output: 'mysticsbiomes:strawberry_jam'},
        {output: 'bakery:dough'},
        {output: 'candlelight:dough'},
        {output: 'create:dough'},
        {output: 'farmingforblockheads:feeding_trough'},
        {output: 'reliquary:midas_touchstone'}, 
        {output: 'reliquary:pyromancer_staff'}, 
        {output: 'reliquary:rod_of_lyssa'},
        {output: 'candlelight:carrot_crate'},
        {output: 'candlelight:potato_crate'},
        {output: 'candlelight:beetroot_crate'}, 
        {output: 'extra_compat:reinforced_gold_knife'},
        {output: 'meadow:climbing_rope_topmount'},
        {output: 'nameless_trinkets:mysterious_trinket'},
        {output: 'herbalbrews:jug'},
        {output: 'forbidden_arcanus:bat_wing'},
        {output: 'plushies:bat_plushie'},
        {output: 'herbalbrews:mixed_tea_leaf_block'},
        {output: 'pipez:energy_pipe'},
        {output: 'pipez:gas_pipe'},
        {output: 'pipez:universal_pipe'},
        {output: 'sophisticatedstorage:feeding_upgrade'},
        {output: 'sophisticatedstorage:advanced_feeding_upgrade'},
        {output: 'sophisticatedstorage:shulker_box'},
        {output: 'sophisticatedstorage:iron_shulker_box'},
        {output: 'sophisticatedstorage:gold_shulker_box'},
        {output: 'sophisticatedstorage:diamond_shulker_box'},
        {output: 'sophisticatedstorage:netherite_shulker_box'},
        {output: 'easy_villagers:converter'},
        {output: 'easy_villagers:iron_farm'},
        {output: 'moblassos:emerald_lasso'},
        {output: 'moblassos:contract'},
        {output: 'functionalstorage:armory_cabinet'},
        {output: 'delightful:jelly_bottle'},
        {output: 'delightful:glow_jelly_bottle'},
        {output: 'delightful:blueberry_sack'},
        {output: 'trashcans:energy_trash_can'},
        {output: 'framedblocks:powered_framing_saw'},
        {output: 'vegandelight:salt'},
        {output: 'reliquary:zombie_heart'},
        {output: 'extra_compat:reinforced_gold_machete'},
        {output: 'sophisticatedbackpacks:inception_upgrade'},
        {output: 'forbidden_arcanus:quantum_catcher'},
        {output: 'tanukidecor:neon_club_sign'},
        {output: 'tanukidecor:neon_diamond_sign'},
        {output: 'tanukidecor:neon_heart_sign'},
        {output: 'tanukidecor:neon_spade_sign'},
        {output: 'tanukidecor:orange_science_pod'},
        {output: 'tanukidecor:green_rocket_lamp'},
        {output: 'tanukidecor:purple_rocket_lamp'},
        {output: 'tanukidecor:pink_rocket_lamp'},
        {output: 'tanukidecor:red_rocket_lamp'},
        {output: 'tanukidecor:turquoise_rocket_lamp'},
        {output: 'tanukidecor:yellow_rocket_lamp'},
        {output: 'tanukidecor:blue_rocket_lamp'},
        {output: 'tanukidecor:minimalist_table'},
        {output: 'tanukidecor:red_science_pod'},
        {output: 'tanukidecor:orange_science_pod'},
        {output: 'tanukidecor:blue_science_pod'},
        {output: 'tanukidecor:green_science_pod'},
        {output: 'tanukidecor:minimalist_dresser'},
        {output: 'tanukidecor:minimalist_mirror'},
        {output: 'tanukidecor:minimalist_wardrobe'},
        {output: 'tanukidecor:regal_armoire'},
        {output: 'tanukidecor:minimalist_stool'},
        {output: 'tanukidecor:minimalist_clock'},
        {output: 'tanukidecor:minimalist_chair'},
        {output: 'tanukidecor:minimalist_couch'},
        {output: 'tanukidecor:minimalist_bed'},
        {output: 'tanukidecor:minimalist_lamp'},
        {output: 'tanukidecor:minimalist_small_table'},
        {output: 'nameless_trinkets:gods_crown'},
        {output: 'sophisticatedbackpacks:smoking_upgrade'},
        {output: 'sophisticatedbackpacks:auto_smoking_upgrade'},
        {output: 'sophisticatedbackpacks:filter_upgrade'},
        {output: 'sophisticatedbackpacks:void_upgrade'},
        {output: 'sophisticatedbackpacks:advanced_void_upgrade'},
        {output: 'sophisticatedbackpacks:advanced_pump_upgrade'},
        {output: 'sophisticatedbackpacks:pump_upgrade'},
        {output: 'sophisticatedbackpacks:advanced_filter_upgrade'},
        {output: 'sophisticatedbackpacks:advanced_deposit_upgrade'},
        {output: 'sophisticatedbackpacks:deposit_upgrade'},
        {output: 'sophisticatedbackpacks:stack_upgrade_tier_4'},
        {output: 'sophisticatedbackpacks:stack_upgrade_tier_3'},
        {output: 'sophisticatedbackpacks:stack_upgrade_tier_2'},
        {output: 'farmingforblockheads:fertilized_farmland_rich'},
        {output: 'farmingforblockheads:fertilized_farmland_rich_stable'},
        {output: 'farmingforblockheads:fertilized_farmland_healthy'},
        {output: 'farmingforblockheads:fertilized_farmland_healthy_stable'},
        {output: 'farmingforblockheads:fertilized_farmland_stable'},
        {output: 'farmingforblockheads:green_fertilizer'},
        {output: 'farmingforblockheads:red_fertilizer'},
        {output: 'farmingforblockheads:yellow_fertilizer'},
        {output: 'farm_and_charm:plow'},
        {output: 'farm_and_charm:supply_cart'},
        {output: 'farm_and_charm:fertilized_soil'},
        {output: 'farm_and_charm:fertilized_farmland'},
        {output: 'farm_and_charm:carrot_bag'},
        {output: 'farm_and_charm:potato_bag'},
        {output: 'farm_and_charm:beetroot_bag'},
        {output: 'farm_and_charm:lamb_ham'},
        {output: 'farm_and_charm:flour'},
        {output: 'farm_and_charm:bacon'},
        {output: 'farm_and_charm:raw_pasta'},
        {output: 'farm_and_charm:minced_beef'},
        {output: 'farm_and_charm:chicken_parts'},
        {output: 'enchanted:witch_cauldron'},
        {output: 'herbalbrews:cauldron'},
        {output: 'farm_and_charm:cooking_pot'},
        {output: 'herbalbrews:copper_tea_kettle'},
        {output: 'herbalbrews:tea_kettle'},
        {output: 'herbalbrews:black_tea_leaf_block'},
        {output: 'herbalbrews:oolong_tea_leaf_block'},
        {output: 'herbalbrews:tea_leaf_crate'},
        {output: 'herbalbrews:green_tea_leaf_block'},
        {output: 'herbalbrews:dried_green_tea_leaf_block'},
        {output: 'herbalbrews:green_tea_leaf'},
        {output: 'farmersrespite:black_tea'},
        {output: 'farmersrespite:long_black_tea'},
        {output: 'farmersrespite:strong_black_tea'},
        {id: 'herbalbrews:brown_dye_from_coffee_beans'},
        {output: 'prefab:item_clutch_of_eggs'},
        { output: 'prefab:block_boundary' },
		{ output: 'prefab:item_bunch_of_beets' },
		{ output: 'prefab:item_bunch_of_carrots' },
		{ output: 'prefab:item_bunch_of_potatoes' },
		{ output: 'prefab:item_clutch_of_eggs' },
		{ output: 'prefab:item_crate_of_beets' },
		{ output: 'prefab:item_crate_of_carrots' },
		{ output: 'prefab:item_crate_of_potatoes' },
		{ output: 'prefab:item_sickle_diamond' },
		{ output: 'prefab:item_sickle_gold' },
		{ output: 'prefab:item_sickle_iron' },
		{ output: 'prefab:item_sickle_netherite' },
		{ output: 'prefab:item_sickle_stone' },
		{ output: 'prefab:item_sickle_wood' },
		{ output: 'prefab:item_swift_blade_bronze' },
		{ output: 'prefab:item_swift_blade_copper' },
		{ output: 'prefab:item_swift_blade_diamond' },
		{ output: 'prefab:item_swift_blade_gold' },
		{ output: 'prefab:item_swift_blade_iron' },
		{ output: 'prefab:item_swift_blade_netherite' },
		{ output: 'prefab:item_swift_blade_obsidian' },
		{ output: 'prefab:item_swift_blade_osmium' },
		{ output: 'prefab:item_swift_blade_steel' },
		{ output: 'prefab:item_swift_blade_stone' },
		{ output: 'prefab:item_swift_blade_wood' },
		{ output: 'prefab:item_wooden_crate' },
        { output: 'hexerei:dowsing_rod'},
        { output: 'hearthandharvest:salt'},
        { output: 'hearthandharvest:salt_bag'},
        { output: 'ae2:nether_quartz_wrench'},
        { output: 'ae2:certus_quartz_wrench'},
        //Replaced Recipes
        {id: 'farmersdelight:wheat_dough_from_water'},
        {id: 'farmersdelight:wheat_dough_from_eggs'},
        {output: 'delightful:cheeseburger'},
        {output: 'delightful:deluxe_cheeseburger'},
        {output: 'luphieclutteredmod:luphie_mermaid_pearl'},
        {output: 'meadow:oil_lantern'},
        {output: 'beautify:hanging_pot'},
        {output: 'pipez:item_pipe'},
        {output: 'tarotcards:tarot_deck'},
        {mod: 'plushies'},
        {mod: 'perfectplushies'},
        {output: 'uncrafter:uncrafter'},
        {id: 'candlelight:mozzarella'},
        {id: 'netherdepthsupgrade:eyeball'},
        {id: 'netherdepthsupgrade:fortress_grouper_plate'},
        {output: 'minecraft:brush'},
        {output: 'betterarcheology:iron_brush'},
        {output: 'betterarcheology:diamond_brush'},
        {output: 'orpheus:apollos_son'},
        {output: 'minecraft:cake'},
        {output: 'delightful:berry_matcha_latte'},
        {id: 'delightful:cooking/matcha_latte'},
        {id: 'delightful:meadow/cooking/matcha_latte'},
        {id: 'delightful:farm_and_charm/pot_cooking/matcha_latte'},
        {id: 'herbalbrews:kettle_brewing/green_tea'},
        {id: 'herbalbrews:kettle_brewing/black_tea'},
        {id: 'herbalbrews:kettle_brewing/lavender_tea'},
        {id: 'herbalbrews:kettle_brewing/hibiscus_tea'},
        {id: 'herbalbrews:kettle_brewing/yerba_mate_tea'},
        {id: 'herbalbrews:kettle_brewing/rooibos_tea'},
        {id: 'farm_and_charm:pot_cooking/nettle_tea'},
        {id: 'farm_and_charm:meadow/cooking/nettle_tea'},
        {output: 'malum:spectral_lens'},
        {id: 'hexerei:leather_from_drying_rack'},
        {type: 'herbalbrews:cauldron_brewing'},
        {type: 'herbalbrews:kettle_brewing'},
        {type: 'meadow:cooking'},
        {type: 'enchanted:witch_cauldron'},
        {type: 'farm_and_charm:pot_cooking'},
        {id: 'hexerei:mahogany_broom_from_mixing_cauldron'},
        {id: 'hexerei:willow_broom_from_mixing_cauldron'},
        {id: 'hexerei:witch_hazel_broom_from_mixing_cauldron'},
        {output: 'prefab:item_carton_of_eggs'},
        {output: 'hexerei:pestle_and_mortar'},
        {output: 'hexerei:mixing_cauldron'},
    
    ];
    
      for (const remove of toRemove) {
        event.remove(remove);
    }

    event.remove({ output: 'minecraft:green_dye', type: 'minecraft:smoking' })
})