StartupEvents.registry('fluid', event => {
	event.create('matcha_green_tea')
		.thinTexture(0xb7f2a0)
		.bucketColor(0xb7f2a0)
		.displayName('Matcha Green Tea')
		.noBucket()
		.noBlock()
	event.create('ceylon_black_tea')
		.thinTexture(0x38260b)
		.bucketColor(0x38260b)
		.displayName('Ceylon Black Tea')
		.noBucket()
		.noBlock()
	event.create('hibiscus_tea')
		.thinTexture(0xd43552)
		.bucketColor(0xd43552)
		.displayName('Hibiscus Tea')
		.noBucket()
		.noBlock()
	event.create('lavender_tea')
		.thinTexture(0x916db0)
		.bucketColor(0x916db0)
		.displayName('Lavender Tea')
		.noBucket()
		.noBlock()
	event.create('yerba_mate_tea')
		.thinTexture(0x34692e)
		.bucketColor(0x34692e)
		.displayName('Yerba Mate Tea')
		.noBucket()
		.noBlock()
	event.create('rooibos_tea')
		.thinTexture(0x823d24)
		.bucketColor(0x823d24)
		.displayName('Rooibos Tea')
		.noBucket()
		.noBlock()
	event.create('oolong_tea')
		.thinTexture(0xa87c48)
		.bucketColor(0xa87c48)
		.displayName('Oolong Tea')
		.noBucket()
		.noBlock()
	event.create('hawberry_tea')
		.thinTexture(0x841A1A)
		.bucketColor(0x841A1A)
		.displayName('Hawberry Tea')
		.noBucket()
		.noBlock()
	event.create('chorus_fruit_milk_tea')
		.thinTexture(0xC37DC3)
		.bucketColor(0xC37DC3)
		.displayName('Chorus Fruit Milk Tea')
		.noBucket()
		.noBlock()
	event.create('chorus_flower_tea')
		.thinTexture(0xC179BE)
		.bucketColor(0xC179BE)
		.displayName('Chorus Flower Tea')
		.noBucket()
		.noBlock()
	event.create('mango_tea')
		.thinTexture(0xFCB028)
		.bucketColor(0xFCB028)
		.displayName('Mango Tea')
		.noBucket()
		.noBlock()
	event.create('peach_tea')
		.thinTexture(0xE48063)
		.bucketColor(0xE48063)
		.displayName('Peach Tea')
		.noBucket()
		.noBlock()
	event.create('lychee_cherry_tea')
		.thinTexture(0xF4B7D9)
		.bucketColor(0xF4B7D9)
		.displayName('Lychee Cherry Tea')
		.noBucket()
		.noBlock()
	event.create('mangosteen_tea')
		.thinTexture(0xEBCAB5)
		.bucketColor(0xEBCAB5)
		.displayName('Mangosteen Tea')
		.noBucket()
		.noBlock()
	event.create('strawberry_tea')
		.thinTexture(0xCA263A)
		.bucketColor(0xCA263A)
		.displayName('Strawberry Tea')
		.noBucket()
		.noBlock()
	event.create('nettle_tea')
		.thinTexture(0x718639)
		.bucketColor(0x718639)
		.displayName('Nettle Tea')
		.noBucket()
		.noBlock()
	event.create('ribwort_tea')
		.thinTexture(0x273A13)
		.bucketColor(0x273A13)
		.displayName('Ribwort Tea')
		.noBucket()
		.noBlock()
})