StartupEvents.registry('item', event => {
	// The texture for this item has to be placed in kubejs/assets/kubejs/textures/item/test_item.png
	// If you want a custom item model, you can create one in Blockbench and put it in kubejs/assets/kubejs/models/item/test_item.json
	

})

StartupEvents.registry('block', event => {

	//Emmu Blocks
	event.create('bat_wallpaper', 'cardinal')
		.model('kubejs:block/bat_wallpaper')
		.soundType('wood')
		.hardness(2)
		.displayName('Bat Wallpaper')
		.tagBlock('minecraft:mineable/axe')

	event.create('skull_wallpaper', 'cardinal')
		.model('kubejs:block/skull_wallpaper')
		.soundType('wood')
		.hardness(2)
		.displayName('Skull Wallpaper')
		.tagBlock('minecraft:mineable/axe')

	event.create('witch_cat_plushie')
		.model('kubejs:block/witch_cat_plushie')
		.soundType('wool')
		.fullBlock(false)
		.defaultCutout()
		.hardness(1.5)
		.displayName('Witch Cat Plushie')

	// Carved Warped Logs
	event.create('carved_warped_1', 'cardinal')
		.model('kubejs:block/carved_warped_1')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Warped Wood Vertical')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_warped_2', 'cardinal')
		.model('kubejs:block/carved_warped_2')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Warped Wood Horizontal')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_warped_3', 'cardinal')
		.model('kubejs:block/carved_warped_3')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Warped Wood Top')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_warped_4', 'cardinal')
		.model('kubejs:block/carved_warped_4')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Warped Wood Bottom')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_warped_5', 'cardinal')
		.model('kubejs:block/carved_warped_5')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Warped Wood Eerie')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_warped_6', 'cardinal')
		.model('kubejs:block/carved_warped_6')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Warped Wood Curve')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_warped_7', 'cardinal')
		.model('kubejs:block/carved_warped_7')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Warped Wood Unsettling')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_warped_8', 'cardinal')
		.model('kubejs:block/carved_warped_8')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Warped Wood Head')
		.tagBlock('minecraft:mineable/axe')

	// Carved Acacia Logs
	event.create('carved_acacia_1', 'cardinal')
		.model('kubejs:block/carved_acacia_1')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Acacia Wood Flower')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_acacia_2', 'cardinal')
		.model('kubejs:block/carved_acacia_2')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Acacia Wood Cross')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_acacia_3', 'cardinal')
		.model('kubejs:block/carved_acacia_3')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Acacia Wood Brace')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_acacia_4', 'cardinal')
		.model('kubejs:block/carved_acacia_4')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Acacia Wood Edge')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_acacia_5', 'cardinal')
		.model('kubejs:block/carved_acacia_5')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Acacia Wood Diamond')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_acacia_6', 'cardinal')
		.model('kubejs:block/carved_acacia_6')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Acacia Wood Lined')
		.tagBlock('minecraft:mineable/axe')

	//TODO - rotation
	event.create('carved_acacia_7', 'cardinal')
		.model('kubejs:block/carved_acacia_7')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Acacia Wood Corner')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_acacia_8', 'cardinal')
		.model('kubejs:block/carved_acacia_8')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Acacia Wood Bracket')
		.tagBlock('minecraft:mineable/axe')

	// Carved Birch Logs
	event.create('carved_birch_1', 'cardinal')
		.model('kubejs:block/carved_birch_1')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Birch Wood Horizontal')
		.tagBlock('minecraft:mineable/axe')

	//TODO - Rotation
	event.create('carved_birch_2', 'cardinal')
		.model('kubejs:block/carved_birch_2')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Birch Wood End Cap')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_birch_3', 'cardinal')
		.model('kubejs:block/carved_birch_3')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Birch Wood Inlay')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_birch_4', 'cardinal')
		.model('kubejs:block/carved_birch_4')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Birch Wood Arched')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_birch_5', 'cardinal')
		.model('kubejs:block/carved_birch_5')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Birch Wood Embossed')
		.tagBlock('minecraft:mineable/axe')

	//TODO - Rotation
	event.create('carved_birch_6', 'cardinal')
		.model('kubejs:block/carved_birch_6')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Birch Wood Corner')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_birch_7', 'cardinal')
		.model('kubejs:block/carved_birch_7')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Birch Wood Fleur de Lis')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_birch_8', 'cardinal')
		.model('kubejs:block/carved_birch_8')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Birch Wood Vertical')
		.tagBlock('minecraft:mineable/axe')

	// Carved Crimson Logs
	event.create('carved_crimson_1', 'cardinal')
		.model('kubejs:block/carved_crimson_1')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Crimson Wood Vertical')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_crimson_2', 'cardinal')
		.model('kubejs:block/carved_crimson_2')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Crimson Wood Horizontal')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_crimson_3', 'cardinal')
		.model('kubejs:block/carved_crimson_3')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Crimson Wood Curve')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_crimson_4', 'cardinal')
		.model('kubejs:block/carved_crimson_4')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Crimson Wood Celestial')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_crimson_5', 'cardinal')
		.model('kubejs:block/carved_crimson_5')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Crimson Wood Lunar')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_crimson_6', 'cardinal')
		.model('kubejs:block/carved_crimson_6')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Crimson Wood Rune Horizontal')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_crimson_7', 'cardinal')
		.model('kubejs:block/carved_crimson_7')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Crimson Wood Rune Vertical')
		.tagBlock('minecraft:mineable/axe')

	//TODO - Rotation
	event.create('carved_crimson_8', 'cardinal')
		.model('kubejs:block/carved_crimson_8')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Crimson Wood Corner')
		.tagBlock('minecraft:mineable/axe')

	// Carved Dark Oak Logs
	event.create('carved_dark_oak_1', 'cardinal')
		.model('kubejs:block/carved_dark_oak_1')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Dark Oak Wood Scales')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_dark_oak_2', 'cardinal')
		.model('kubejs:block/carved_dark_oak_2')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Dark Oak Wood Clouds')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_dark_oak_3', 'cardinal')
		.model('kubejs:block/carved_dark_oak_3')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Dark Oak Wood Dragon Horizontal')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_dark_oak_4', 'cardinal')
		.model('kubejs:block/carved_dark_oak_4')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Dark Oak Wood Dragon Head')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_dark_oak_5', 'cardinal')
		.model('kubejs:block/carved_dark_oak_5')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Dark Oak Wood Dragon Vertical')
		.tagBlock('minecraft:mineable/axe')

	//TODO - rotation
	event.create('carved_dark_oak_6', 'cardinal')
		.model('kubejs:block/carved_dark_oak_6')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Dark Oak Wood Dragon Leg')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_dark_oak_7', 'cardinal')
		.model('kubejs:block/carved_dark_oak_7')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Dark Oak Wood Dragon Tail')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_dark_oak_8', 'cardinal')
		.model('kubejs:block/carved_dark_oak_8')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Dark Oak Wood Oni')
		.tagBlock('minecraft:mineable/axe')

	// Carved Spruce Logs
	event.create('carved_spruce_1', 'cardinal')
		.model('kubejs:block/carved_spruce_1')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Spruce Wood Eagle')
		.tagBlock('minecraft:mineable/axe')

	//TODO - Rotation
	event.create('carved_spruce_2', 'cardinal')
		.model('kubejs:block/carved_spruce_2')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Spruce Wood Wing')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_spruce_3', 'cardinal')
		.model('kubejs:block/carved_spruce_3')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Spruce Wood Talons')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_spruce_4', 'cardinal')
		.model('kubejs:block/carved_spruce_4')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Spruce Wood Villager')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_spruce_5', 'cardinal')
		.model('kubejs:block/carved_spruce_5')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Spruce Wood Paws')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_spruce_6', 'cardinal')
		.model('kubejs:block/carved_spruce_6')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Spruce Wood Beast')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_spruce_7', 'cardinal')
		.model('kubejs:block/carved_spruce_7')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Spruce Wood Horizontal')
		.tagBlock('minecraft:mineable/axe')

	event.create('carved_spruce_8', 'cardinal')
		.model('kubejs:block/carved_spruce_8')
		.soundType('wood')
		.hardness(2)
		.displayName('Carved Spruce Wood Vertical')
		.tagBlock('minecraft:mineable/axe')

	//New Carved Woods from Os

	    // Carved Acacia
		event.create('acacia_carved_column', 'cardinal')
		.model('kubejs:block/acacia_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Acacia Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('acacia_carved_parquet', 'cardinal')
		.model('kubejs:block/acacia_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Acacia Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('acacia_stripped_carved_column', 'cardinal')
		.model('kubejs:block/acacia_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Acacia Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Bamboo
		event.create('bamboo_carved_mosaic', 'cardinal')
		.model('kubejs:block/bamboo_carved_mosaic')
		.soundType('wood')
		.hardness(2)
		.displayName('Bamboo Carved Mosaic')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('bamboo_carved_parquet', 'cardinal')
		.model('kubejs:block/bamboo_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Bamboo Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Birch
		event.create('birch_carved_column', 'cardinal')
		.model('kubejs:block/birch_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Birch Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('birch_carved_parquet', 'cardinal')
		.model('kubejs:block/birch_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Birch Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('birch_stripped_carved_column', 'cardinal')
		.model('kubejs:block/birch_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Birch Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Cherry
		event.create('cherry_carved_column', 'cardinal')
		.model('kubejs:block/cherry_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Cherry Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('cherry_carved_parquet', 'cardinal')
		.model('kubejs:block/cherry_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Cherry Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('cherry_stripped_carved_column', 'cardinal')
		.model('kubejs:block/cherry_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Cherry Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Crimson
		event.create('crimson_carved_column', 'cardinal')
		.model('kubejs:block/crimson_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Crimson Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('crimson_carved_parquet', 'cardinal')
		.model('kubejs:block/crimson_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Crimson Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('crimson_stripped_carved_column', 'cardinal')
		.model('kubejs:block/crimson_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Crimson Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Dark Oak
		event.create('dark_oak_carved_column', 'cardinal')
		.model('kubejs:block/dark_oak_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Dark Oak Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('dark_oak_carved_parquet', 'cardinal')
		.model('kubejs:block/dark_oak_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Dark Oak Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('dark_oak_stripped_carved_column', 'cardinal')
		.model('kubejs:block/dark_oak_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Dark Oak Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Jungle
		event.create('jungle_carved_column', 'cardinal')
		.model('kubejs:block/jungle_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Jungle Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('jungle_carved_parquet', 'cardinal')
		.model('kubejs:block/jungle_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Jungle Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('jungle_stripped_carved_column', 'cardinal')
		.model('kubejs:block/jungle_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Jungle Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Mangrove
		event.create('mangrove_carved_column', 'cardinal')
		.model('kubejs:block/mangrove_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Mangrove Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('mangrove_carved_parquet', 'cardinal')
		.model('kubejs:block/mangrove_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Mangrove Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('mangrove_stripped_carved_column', 'cardinal')
		.model('kubejs:block/mangrove_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Mangrove Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Oak
		event.create('oak_carved_column', 'cardinal')
		.model('kubejs:block/oak_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Oak Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('oak_carved_parquet', 'cardinal')
		.model('kubejs:block/oak_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Oak Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('oak_stripped_carved_column', 'cardinal')
		.model('kubejs:block/oak_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Oak Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Pale Oak
		event.create('pale_oak_carved_column', 'cardinal')
		.model('kubejs:block/pale_oak_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Pale Oak Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('pale_oak_carved_parquet', 'cardinal')
		.model('kubejs:block/pale_oak_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Pale Oak Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('pale_oak_stripped_carved_column', 'cardinal')
		.model('kubejs:block/pale_oak_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Pale Oak Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Spruce
		event.create('spruce_carved_column', 'cardinal')
		.model('kubejs:block/spruce_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Spruce Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('spruce_carved_parquet', 'cardinal')
		.model('kubejs:block/spruce_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Spruce Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('spruce_stripped_carved_column', 'cardinal')
		.model('kubejs:block/spruce_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Spruce Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		// Carved Warped
		event.create('warped_carved_column', 'cardinal')
		.model('kubejs:block/warped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Warped Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('warped_carved_parquet', 'cardinal')
		.model('kubejs:block/warped_carved_parquet')
		.soundType('wood')
		.hardness(2)
		.displayName('Warped Carved Parquet')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)
	
		event.create('warped_stripped_carved_column', 'cardinal')
		.model('kubejs:block/warped_stripped_carved_column')
		.soundType('wood')
		.hardness(2)
		.displayName('Stripped Warped Carved Column')
		.tagBlock('minecraft:mineable/axe')
		.tagBoth('minecraft:logs')
		.fullBlock(true)

})