#Blocks (Default: 65)
"Short Threshold" = 65
#Blocks (Default: 90)
"Medium Threshold" = 90
#Blocks (Default: 115)
"Far Threshold" = 115
#Ticks (Default: 40)
"Close Delay" = 40
#Ticks (Default: 70)
"Medium Delay" = 85
#Ticks (Default: 130)
"Far Delay" = 130

