
[items]

	[items.compass]
		#Compasses display X and Z coordinates in the item description
		"Compasses display position" = true

	[items.clock]
		#Clocks display the time of day in the item description
		"Clocks display time" = true
		#Clocks display the what day it is in the item description
		"Clocks display day" = true
		#Clocks use 24-hour time if displaying the time
		"Clocks use 24-hour time" = false

	[items.depth_gauge]
		#Depth Gauges display Y coordinates in the item description
		"Depth Gauges display position" = true

	[items.barometer]
		#Barometers display the weather in the item description
		"Barometers display weather" = true

