
[blocks]
	Kiln = true
	"Chiseled bricks" = true
	"Glazed terracotta" = true
	Concrete = true
	"Terracotta slabs, stairs, and walls" = true
	"Terracotta bricks" = true

	[blocks.decorated_pot]
		"Decorated pot colors" = true
		"Decorated pot trims" = true

