
[dropRush]
	#The base chance for a drop rush to occur.
	baseChance = 0.019999999552965164

[goldRush]
	#The base chance for a gold rush to occur.
	baseChance = 0.019999999552965164

[fishingSpots]
	#The minimum distance between fishing spots, preventing them from spawning too close together.
	minimumDistanceBetween = 128
	#The distance fishing spots will spawn from the player.
	spawnDistance = 8
	#The seconds that must pass after a fishing spot appeared before another fishing spot can appear for a player.
	spawnIntervalSeconds = 300.0
	#The seconds that must pass after fishing a fishing spot before another fishing spot can appear for a player.
	afterFishingCooldownSeconds = 600.0
	#The maximum distance a bobber can be from a fishing spot to still trigger it.
	fishingRangeTolerance = 3
	#Fishing spots will lure fish quicker than regular water. Set to -1 to disable.
	secondsUntilLured = 2.0
	#The limit of fishing spots that can spawn in a given chunk overall. Once this many fishing spots have spawned, the chunk will never spawn any again. Set to -1 to disable.
	totalLimitPerChunk = -1
	#The offset applied to the spawn area in the direction the player is facing. Set to 0 to center it around the player.
	projectForwardDistance = 4

[digSpots]
	#The minimum distance between dig spots, preventing them from spawning too close together.
	minimumDistanceBetween = 128
	#The distance dig spots will spawn from the player.
	spawnDistance = 32
	#The seconds that must pass after a dig spot appeared before another dig spot can appear for a player.
	spawnIntervalSeconds = 300.0
	#The seconds that must pass after digging a dig spot before another dig spot can appear for a player.
	afterDiggingCooldownSeconds = 600.0
	#The limit of dig spots that can spawn in a given chunk overall. Once this many dig spots have spawned, the chunk will never spawn any again. Set to -1 to disable.
	totalLimitPerChunk = 1
	#The offset applied to the spawn area in the direction the player is facing. Set to 0 to center it around the player.
	projectForwardDistance = 25

