
["Configs for Orpheus Mod"]
	#If you input "keep" it will give you the KeepInventory effect. If you input "protect" it will grant you immunity to arrows. If you input the word "both", you will have both effects.
	"Orpheus Lyre Power" = "keep"
	#If true, the Orpheus Lyre will be consumed (broken) when its keep-inventory effect is applied. If false, the Lyre will not be consumed and can be used repeatedly.
	"Orpheus Lyre One Time Use" = false

