#id, 
#spawn timer in seconds, 
#min group number, 
#max group number, 
#max number of untamed skunk in an area, 
#spawn time (0->only in light 1->only in dark 2->can spawn anytime), 
#biome
striped = "0, 180, 1, 1, 5, 0, biomes=minecraft:forest, minecraft:flower_forest, minecraft:old_growth_spruce_taiga"
hooded = "1, 240, 1, 1, 5, 0, biomes=minecraft:forest, minecraft:flower_forest, minecraft:old_growth_spruce_taiga"
vanilla = "2, 360, 1, 1, 5, 0, biomes=minecraft:forest, minecraft:flower_forest, minecraft:old_growth_spruce_taiga"
albino = "3, 200, 1, 1, 5, 0, biomes=minecraft:snowy_taiga"
ghost = "5, 220, 1, 1, 5, 2, biomes=minecraft:soul_sand_valley"
end = "6, 190, 1, 1, 5, 2, biomes=betterend:chorus_forest"
endvoid = "7, 250, 1, 1, 5, 2, biomes=minecraft:the_end, minecraft:end_highlands, minecraft:end_midlands, minecraft:end_barrens, minecraft:small_end_islands"
nether = "8, 195, 1, 1, 5, 2, biomes=minecraft:nether_wastes"
mushroom = "9, 185, 1, 1, 5, 2, biomes=minecraft:crimson_forest, minecraft:warped_forest"
dragon = "12, 180, 1, 1, 2, 2, biomes=minecraft:nether_wastes"

