
["Tameable Beasts Configs"]
	#Spawn Chikote
	"Chikotes enabled:" = true
	#Spawn Flying Beetle
	"Flying Beetles enabled:" = true
	#Spawn Roly Poly
	"Roly Polys enabled:" = true
	#Spawn Grasshopper
	"Grasshoppers enabled:" = false
	#Spawn Ground Beetle
	"Ground Beetles enabled:" = true
	#Spawn Penguin
	"Penguins enabled:" = true
	#Spawn QuetzalCoatulus
	"QuetzalCoatuluss enabled:" = true
	#Spawn Racoon
	"Racoons enabled:" = true
	#Spawn Crested Gecko
	"Crested Geckos enabled:" = true
	#Spawn Argentavis Gecko
	"Argentavis enabled:" = true

